spring:
  datasource:
    url: ${SPRING_DATASOURCE_URL}
    username: ${SPRING_DATASOURCE_USERNAME}
    password: ${SPRING_DATASOURCE_PASSWORD}
    driver-class-name: org.postgresql.Driver
  data:
    redis:
      host: ${SPRING_DATA_REDIS_HOST}
      port: ${SPRING_DATA_REDIS_PORT}
  mail:
    host: ${MAIL_HOST}
    port: ${MAIL_PORT}
    username: ${MAIL_USERNAME}
    password: ${MAIL_PASSWORD}
    properties.mail.smtp:
      ssl.enable: ${MAIL_SMTP_SSL_ENABLE}
      starttls.enable: ${MAIL_SMTP_STARTTLS_ENABLE}

jwt:
  secret: ${JWT_SECRET}
  refresh-token-expiration-time: ${JWT_REFRESH_TOKEN_EXPIRATION_TIME}
  access-token-expiration-time: ${JWT_ACCESS_TOKEN_EXPIRATION_TIME}

verification-code-expiration-time: ${VERIFICATION_CODE_EXPIRATION_TIME} # Minutes
