spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/YOUR_DATABASE_NAME
    username: YOUR_DATABASE_USERNAME
    password: YOUR_DATABASE_PASSWORD
    driver-class-name: org.postgresql.Driver
  data:
    redis:
      port: 6379
      host: localhost
  mail:
    host: YOUR_MAIL_HOST
    port: 1111 # Replace it with the actual port
    username: YOUR_MAIL_USERNAME
    password: YOUR_MAIL_PASSWORD
    properties.mail.smtp:
      ssl.enable: false
      starttls.enable: true

jwt:
  secret: YOUR_JWT_SECRET_KEY
  refresh-token-expiration-time: 240000 # In milliseconds
  access-token-expiration-time: 120000 # In milliseconds

verification-code-expiration-time: 2 # In minutes