server.port: 8085
logging.level.org.springframework.security: DEBUG

spring:
  application.name: user-service
  main.banner-mode: off
  datasource:
    url: ${SPRING_DATASOURCE_URL:jdbc:postgresql://postgres:5432/protu-db}
    username: ${SPRING_DATASOURCE_USERNAME:postgres}
    password: ${SPRING_DATASOURCE_PASSWORD:password}
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate.ddl-auto: update
    show-sql: false
    properties.hibernate.format_sql: false

springdoc:
  api-docs.enabled: true
  swagger-ui:
    enabled: true
    path: /swagger-ui.html

jwt:
  secret: ${JWT_SECRET:verySecureJwtSecretKeyThatIsAtLeast32BytesLong12345678901234567890}
  refresh-token-expiration-time: ${JWT_REFRESH_TOKEN_EXPIRATION_TIME:240000}
  access-token-expiration-time: ${JWT_ACCESS_TOKEN_EXPIRATION_TIME:120000}

verification-code-expiration-time: ${VERIFICATION_CODE_EXPIRATION_TIME:2} # Minutes

spring.mail:
  host: sandbox.smtp.mailtrap.io
  port: 2525
  username: f7942f3fc06991
  password: 2b25b85dbbadc1
  properties.mail.smtp.ssl.enable: false
  properties.mail.smtp.starttls.enable: true