app:
  api-version: v1

spring:
  profiles:
    active: local
  application.name: content-service
  main:
    banner-mode: off

  jpa:
    open-in-view: false
    show-sql: false
    properties:
      hibernate:
        format_sql: false
    hibernate:
      ddl-auto: update

  data:
    rest:
      base-path: /api

server:
  port: 8087
