app:
  api.version: v1

server.port: 8087

spring:
  profiles.active: local
  application.name: content-service
  main.banner-mode: off

  jpa:
    open-in-view: false
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    hibernate:
      ddl-auto: update
  